### ISSUE TITLE
unclear source of the data/complemented-datasets folder

### ISSUE THREAD

**Issue by vlosing** [SapienzaNLP/consec#1]
When I try to train the model I get the following error. It is unclear to me where the complemented datasets are coming from. They are not contained in the Raganto files. Can you please specify the origin of those?

FileNotFoundError: Error instantiating 'src.disambiguation_corpora.WordNetCorpus' : [Errno 2] No such file or directory: 'data/complemented-datasets/semeval2007/semeval2007.gold.key.txt'

**Comment by poccio** [comment]
Hi! First of all, thank you for your interest in this project!

"complemented-datasets" was something we experimented on, but that didn't make it in the paper. You can just delete those lines in the callback config. I also pushed the fixed .yaml file so you can check it out (I tested it and the model trains).
