### ISSUE TITLE
Unable to find WNGT files.

### ISSUE THREAD

**Issue by sonodasong** [SapienzaNLP/consec#2]
Hello, I am interested in your project and want to try it out.

However, when I tried the experiment with WNGT, I got the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/WSD_Evaluation_Framework/Training_Corpora/WNG/glosses_main.gold.key.txt'`
The reason is that `WSD_Evaluation_Framework` folder does not contain `WNG` and `WNE` folders and their files.

Please advise where to find these files. Thank you.

**Comment by sonodasong** [comment]
By the way, when WNGT is used for training, do you also limit the number of maximum training steps to 100,000? Or larger?
Thanks.

**Comment by poccio** [comment]
Hi! First of all, I am glad to hear you are interested in this project!

You are right, WNG and WNE are not included in the standard WSD framework (the one automatically downloaded in _data/WSD_Evaluation_Framework_). I updated [setup.sh](https://setup.sh/) to also download these files (which we retrieve from EWISER (Bevilacqua and Navigli, 2020)). If you prefer not to re-run this script, you can checkout the nested *if* I added at the end of the file.

As regards your second question, the number of maximum training steps is left to 1_000_000 also when using WNGT.

Finally, thanks to this issue we realized we hadn't uploaded yet the SemCor+WNGT checkpoint. If you are interested in this checkpoint, check out the README (we just put a download link).

Let me know if you have any further problem/question, or if I can close the issue.

**Comment by sonodasong** [comment]
Hi, thanks for clarifying!
> By the way, when WNGT is used for training, do you also limit the number of maximum training steps to 100,000? Or larger?

I put 100,000 in the question because the original paper says 100,000 in Section 4.1 on page 1496.
>As regards your second question, the number of maximum training steps is left to 1_000_000 also when using WNGT.

Does 1_000_000 mean 1,000,000?
Thanks.

**Comment by edobobo** [comment]
Yes, in Section 4.1 we reported the configuration for the SemCor-only training process, and yes 1_000_000 means 1,000,000.
